version: "3.9"

services:
  mongodb:
    image: mongo:8
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - benyan-network

  backend:
    image: mohamedadel204/benyan-backend:1.0
    build:
      context: ./BackEnd
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./BackEnd:/app
      - /app/node_modules
    env_file:
      - ./BackEnd/config/config.env
    depends_on:
      - mongodb
    networks:
      - benyan-network

  frontend:
    image: mohamedadel204/benyan-frontend:1.0
    build:
      context: ./FrontEnd
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "5173:5173"
    volumes:
      - ./FrontEnd:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - benyan-network

volumes:
  mongodb_data:

networks:
  benyan-network:
    driver: bridge